version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "shippop"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "root"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    #   - ./deploy/init-mysql.sql:/docker-entrypoint-initdb.d
  api:
    ports:
      - "5000:5000"
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file: .env
    environment:
      - NODE_PORT=5000
    depends_on:
      - db
volumes:
  my-db:
